language: php

php:
  - 7.4

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mkdir public
  - touch public/index.php
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
    - travis_retry php vendor/bin/php-coveralls
    - travis_retry php vendor/bin/psalm --shepherd
